using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace Downloader.Desktop.Services;

/// <summary>One cookie as the browser extension's <c>chrome.cookies.getAll</c> returns it.</summary>
public sealed class CookieDto
{
    public string Name { get; set; }
    public string Value { get; set; }
    public string Domain { get; set; }
    public string Path { get; set; } = "/";
    public bool Secure { get; set; }
    /// <summary>Unix epoch seconds; null/absent = a session cookie (written as expiry 0).</summary>
    public long? Expires { get; set; }
}

/// <summary>
/// Writes a browser-supplied cookie list to a short-lived temp file in the Netscape cookie-file format that
/// yt-dlp's <c>--cookies FILE</c> understands. Cookies are secrets: the file goes to the OS temp dir with
/// the most restrictive permissions the platform allows, and the caller deletes it right after use. The
/// formatting is a pure function (<see cref="ToNetscape"/>) so it can be unit-tested without touching disk.
/// </summary>
public static class CookieFile
{
    /// <summary>Render the Netscape cookie-file text for a cookie list. Never logs values.</summary>
    public static string ToNetscape(IEnumerable<CookieDto> cookies)
    {
        var sb = new StringBuilder();
        sb.Append("# Netscape HTTP Cookie File\n");
        sb.Append("# Auto-generated by Downloader for a single download; do not edit.\n");
        foreach (var c in cookies)
        {
            if (c == null || string.IsNullOrEmpty(c.Name) || string.IsNullOrEmpty(c.Domain))
                continue;
            var domain = c.Domain.Trim();
            // A leading dot means "and subdomains" in the Netscape format's include-subdomains flag.
            var includeSub = domain.StartsWith(".", StringComparison.Ordinal) ? "TRUE" : "FALSE";
            var path = string.IsNullOrEmpty(c.Path) ? "/" : c.Path;
            var secure = c.Secure ? "TRUE" : "FALSE";
            var expiry = (c.Expires is > 0 ? c.Expires.Value : 0).ToString(CultureInfo.InvariantCulture);
            // Tab-separated: domain, include-subdomains, path, secure, expiry, name, value.
            sb.Append(domain).Append('\t')
              .Append(includeSub).Append('\t')
              .Append(path).Append('\t')
              .Append(secure).Append('\t')
              .Append(expiry).Append('\t')
              .Append(c.Name).Append('\t')
              .Append(c.Value ?? string.Empty).Append('\n');
        }
        return sb.ToString();
    }

    /// <summary>Write the cookies to a new temp file (restrictive perms) and return its path.</summary>
    public static string WriteTempFile(IEnumerable<CookieDto> cookies)
    {
        var path = System.IO.Path.Combine(
            System.IO.Path.GetTempPath(), "dldl-cookies-" + Guid.NewGuid().ToString("N") + ".txt");
        File.WriteAllText(path, ToNetscape(cookies));
        TryRestrictPermissions(path);
        return path;
    }

    private static void TryRestrictPermissions(string path)
    {
        // On Unix, lock the file down to owner read/write (0600). Windows temp dir is already user-scoped.
        try
        {
            if (!OperatingSystem.IsWindows())
                File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }
        catch { /* best effort — never block a download on chmod */ }
    }
}
