namespace Downloader.Desktop.Models;

/// <summary>
/// One browser target from <c>extension-catalog.json</c>, the asset the release workflow publishes next
/// to the extension zips (generated by <c>scripts/build-extension.sh</c> from the zips themselves, so its
/// checksums cannot disagree with them).
/// </summary>
public sealed class ExtensionCatalogEntry
{
    /// <summary>Target key — <c>chrome</c> or <c>firefox</c>. Also the folder the build is unpacked into.</summary>
    public string Id { get; init; }

    /// <summary><c>chromium</c> or <c>gecko</c>: decides which install steps and limitations apply.</summary>
    public string Family { get; init; }

    /// <summary>The browsers this build covers, as shown to the user.</summary>
    public string Name { get; init; }

    /// <summary>The extension version in this build (read from that target's manifest at build time).</summary>
    public string Version { get; init; }

    public string AssetName { get; init; }

    /// <summary>Resolved from the release's own asset list — an entry naming an asset the release does not
    /// carry is dropped rather than offered.</summary>
    public string AssetUrl { get; init; }

    /// <summary>Lowercase hex SHA-256 of the asset. Verified BEFORE anything is extracted.</summary>
    public string Sha256 { get; init; }

    /// <summary>Oldest app version whose local API can serve this build; entries this app is too old for
    /// are not offered (same gate as the optional-plugin catalog).</summary>
    public string MinAppVersion { get; init; }

    /// <summary>The published store listing, or null when there is none. Null is what makes the app offer
    /// the manual "load unpacked" path instead.</summary>
    public string StoreUrl { get; init; }

    /// <summary>True when a store listing is published for this target.</summary>
    public bool HasStore => !string.IsNullOrWhiteSpace(StoreUrl);
}
